export const GET_BRANDS_FEATURED_SUCCESS = "GET_BRANDS_FEATURED_SUCCESS";
export const GET_BRANDS_FEATURED_FAIL = "GET_BRANDS_FEATURED_FAIL";
export const GET_CATEGORY_TRENDING_SUCCESS = "GET_CATEGORY_TRENDING_SUCCESS";
export const GET_CATEGORY_TRENDING_FAIL = "GET_CATEGORY_TRENDING_FAIL";
export const GET_LIST_PRODUCT_NEW_SUCCESS = "GET_LIST_PRODUCT_NEW_SUCCESS";
export const GET_LIST_PRODUCT_NEW_FAIL = "GET_LIST_PRODUCT_NEW_FAIL";
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';
